"""
Data models for aromatherapy system.
Uses Pydantic for validation and SQLAlchemy for database ORM.
"""
from datetime import datetime
from typing import Optional, Dict, Literal
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field, model_validator
from sqlalchemy import Column, String, Text, Integer, JSON, DateTime
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func
import uuid


# SQLAlchemy Base
Base = declarative_base()


# Type Aliases
ScentType = Literal["lemon", "lavender", "woody", "floral", "mixed"]
ReleaseRhythm = Literal["gradual", "pulse", "intermittent"]
CommandStatus = Literal["pending", "executed", "failed"]


# Pydantic Models (for API validation)

class MixingRatios(BaseModel):
    """Scent mixing ratios (sum should be ~1.0)."""
    lemon: Optional[float] = Field(None, ge=0, le=1)
    lavender: Optional[float] = Field(None, ge=0, le=1)
    woody: Optional[float] = Field(None, ge=0, le=1)
    floral: Optional[float] = Field(None, ge=0, le=1)


class ControlJson(BaseModel):
    """
    Structured control parameters for aromatherapy device.
    Generated by LLM from natural language input.
    """
    scent_type: ScentType = Field(..., description="Primary or mixed scent type")
    intensity: int = Field(..., ge=1, le=10, description="Scent intensity level (1-10)")
    duration_minutes: int = Field(..., ge=5, le=120, description="Duration in minutes (5-120)")
    release_rhythm: ReleaseRhythm = Field(..., description="Release pattern")
    mixing_ratios: Optional[MixingRatios] = Field(None, description="Scent mixing ratios (for mixed type)")

    @model_validator(mode="after")
    def validate_mixing_for_mixed_scent(self):
        """If scent_type is 'mixed', mixing_ratios must be provided."""
        if self.scent_type == "mixed" and self.mixing_ratios is None:
            raise ValueError("mixing_ratios required when scent_type is 'mixed'")
        return self


class CommandCreate(BaseModel):
    """Request model for creating a new command."""
    user_input_text: str = Field(..., min_length=1, max_length=1000)


class CommandResponse(BaseModel):
    """Response model for command data."""
    id: UUID
    created_at: datetime
    user_input_text: str
    llm_response_text: Optional[str]
    control_json: ControlJson
    tts_audio_url: Optional[str]
    status: CommandStatus
    execution_error: Optional[str]
    user_feedback: Optional[int]
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class FeedbackUpdate(BaseModel):
    """Request model for updating user feedback."""
    user_feedback: int = Field(..., ge=1, le=5, description="Rating 1-5 stars")


# SQLAlchemy Models (for database)

class AromatherapyCommand(Base):
    """
    Database model for aromatherapy commands.
    Stores user input, LLM responses, control parameters, and execution status.
    """
    __tablename__ = "aromatherapy_commands"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # User input and LLM response
    user_input_text = Column(Text, nullable=False)
    llm_response_text = Column(Text, nullable=True)

    # Control parameters (JSONB)
    control_json = Column(JSON, nullable=False)

    # TTS audio
    tts_audio_url = Column(Text, nullable=True)

    # Execution status
    status = Column(String(20), nullable=False, default="pending")
    execution_error = Column(Text, nullable=True)

    # User feedback
    user_feedback = Column(Integer, nullable=True)

    # Timestamps
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "id": str(self.id),
            "created_at": self.created_at.isoformat(),
            "user_input_text": self.user_input_text,
            "llm_response_text": self.llm_response_text,
            "control_json": self.control_json,
            "tts_audio_url": self.tts_audio_url,
            "status": self.status,
            "execution_error": self.execution_error,
            "user_feedback": self.user_feedback,
            "updated_at": self.updated_at.isoformat(),
        }
